dist: xenial
language: node_js

node_js:
  - '14'
  - '12'
  - '10'
  - '8'
  - '6'
  - '5'
  - '4'
  - '3'
  - '2'
  - '1'
  - '0.12'
  - '0.10'

env:
  - MONGODB_VERSION=2.6
  - MONGODB_VERSION=3.0
  - MONGODB_VERSION=3.2
  - MONGODB_VERSION=3.4
  - MONGODB_VERSION=3.6
  - MONGODB_VERSION=4.0
  - MONGODB_VERSION=4.2

before_install:
  # we have to install mongo-orchestration ourselves to get around permissions issues in subshells
  - sudo pip install --upgrade 'git+git://github.com/mongodb/mongo-orchestration@master'
  - sudo apt-get install -y libsnmp30

  - git clone --depth 1 https://github.com/mongodb-labs/drivers-evergreen-tools
  - export DRIVERS_TOOLS="${PWD}/drivers-evergreen-tools"
  - export MONGO_ORCHESTRATION_HOME="$DRIVERS_TOOLS/.evergreen/orchestration"
  - export MONGODB_BINARIES="$DRIVERS_TOOLS/mongodb/bin"

  # disable ipv6 since its not supported on travis
  - "find ${MONGO_ORCHESTRATION_HOME} -name \"*.json\" -exec sed -i 's/\"ipv6\": true/\"ipv6\": false/g' {} \\;"
  - "find ${MONGO_ORCHESTRATION_HOME} -name \"*.json\" -exec sed -i 's/,::1//g' {} \\;"
  - "find ${MONGO_ORCHESTRATION_HOME} -name \"*.json\" -exec sed -i 's/::1,//g' {} \\;"

  - "echo '{ \"releases\": { \"default\": \"'${MONGODB_BINARIES}'\" } }' > $MONGO_ORCHESTRATION_HOME/orchestration.config"
  - bash ${DRIVERS_TOOLS}/.evergreen/run-orchestration.sh || tail -n +1 ${MONGO_ORCHESTRATION_HOME}/*.log
  - "export MONGODB_URI=$(grep -oP '(?<=MONGODB_URI: \")[^\"]*' mo-expansion.yml)"
